FROM node:18-alpine

WORKDIR /app
COPY ./frontend ./frontend
COPY ./common ./common
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=80

EXPOSE 80
EXPOSE 24678

WORKDIR /app/frontend
RUN npm install
ENTRYPOINT ["npm", "run", "dev"]
