FROM node:16.15.1-alpine

WORKDIR /app

COPY ./frontend/entrypoint.dev.sh /scripts/
RUN chmod +x -R /scripts

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000
EXPOSE 24678

ENTRYPOINT ["sh", "/scripts/entrypoint.dev.sh"]
