version: '3.7'

x-logging: &default-logging
    driver: json-file
    options:
        max-size: '10m'
        max-file: '5'

services:
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
            args:
                - NODE_ENV=production
                - VITE_API_URL=http://backend:7080/api
                - VITE_BASE_URL=http://backend:7080
                - VITE_IPREGISTRY_API_KEY=ryy5dlbl3v8y55x4
                - VITE_AUTH_SERVER_URL=https://auth.poster-test-peredelano.orby-tech.space
                - VITE_POSTAUTH_URL=http://backend:3000
                - TELEGRAM_AUTH_BOT_NAME=afisha_oauth_local_bot
        logging: *default-logging
        ports:
            - 80:3000
        links:
            - backend

    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile.dev
        logging: *default-logging
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            - FRONTEND_URL=http://127.0.0.1
        ports:
            - '7080:7080'
        volumes:
            - ./:/app

    mongo:
        image: mongo:6.0
        restart: unless-stopped
        command: ['--bind_ip_all']
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
            interval: 10s
            start_period: 30s
        ports:
            - '27020:27017'
        volumes:
            - /tmp/ows-events/db:/data/db
