version: '3.7'

x-logging: &default-logging
    driver: json-file
    options:
        max-size: '10m'
        max-file: '5'

networks:
    traefikpublic:

services:
    traefik:
        image: traefik:v2.4
        logging: *default-logging
        container_name: 'traefik'
        restart: always
        command:
            - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
            - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http'
            - '--certificatesresolvers.myresolver.acme.email=afisha.peredelano@proton.me'
            - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
            - '--providers.docker=true'
            - '--providers.docker.network=ows-events_test_traefikpublic'
            - '--providers.docker.endpoint=unix:///var/run/docker.sock'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.http.address=:80'
            - '--entrypoints.https.address=:443'
            - '--api=true'
            - '--api.basePath=/traefik'
            - '--accesslog=true'
            - '--metrics.prometheus=true'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_ADMIN_USER}:${TRAEFIK_ADMIN_HASHED_PASSWORD}'
            - 'traefik.http.routers.dashboard.rule=Host(`afisha.peredelano.com`) && PathPrefix(`/traefik`)'
            - 'traefik.http.routers.dashboard.service=api@internal'
            - 'traefik.http.routers.dashboard.entrypoints=https'
            - 'traefik.http.routers.dashboard.tls.certresolver=myresolver'
            - 'traefik.http.routers.dashboard.middlewares=auth'
            - 'traefik.http.routers.metrics.rule=Host(`afisha.peredelano.com`) && PathPrefix(`/prometheus`)'
            - 'traefik.http.routers.metrics.tls=true'
            - 'traefik.http.routers.metrics.tls.certresolver=myresolver'
            - 'traefik.http.routers.metrics.service=prometheus@internal'
            - 'traefik.http.routers.metrics.middlewares=auth'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './letsencrypt:/letsencrypt'
        ports:
            - mode: host
              protocol: tcp
              published: 80
              target: 80
            - mode: host
              protocol: tcp
              published: 443
              target: 443
        networks:
            - traefikpublic
