export enum RoutePathEnum {
	HOME = '/',
	EVENT = '/event',
	AUTH = '/auth',
	EVENT_EDIT = '/event/edit-',
	ABOUT = '/about',
	DONATION = '/donate',
	PAYMENT_INFO = '/payment/',
	LIMITATION_OF_LIABILITY = '/limitation-of-liability',
	USER_PAGE = '/user',
	USER_FAVOURITES = '/user/favourites',
	USER_MY_EVENTS = '/user/my-events',
	USER_PROFILE = '/user/profile',
	SUPPORT = '/support',
	COOPERATION = '/cooperation',
}

export enum RouteNameEnum {
	HOME = 'index',
	EVENT = 'event-id',
	AUTH = 'auth',
	ABOUT = 'about',
	DONATION = 'donate',
	PAYMENT_INFO = 'payment-eventId',
	LIMITATION_OF_LIABILITY = 'limitation-of-liability',
	USER_PAGE = 'user',
	USER_FAVOURITES = 'user-favourites',
	USER_MY_EVENTS = 'user-my-events',
	EVENT_EDIT = 'event-edit-editId',
	USER_PROFILE = 'user-profile',
	SUPPORT = 'support',
	COOPERATION = 'cooperation',
}
