name: CodeReview at MergeRequest

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check code syntax
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DISABLE_ERRORS: false
          LOG_LEVEL: WARN
          VALIDATE_ALL_CODEBASE: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GITLEAKS: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_YAML: true
          VALIDATE_SQL: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_GITHUB_ACTIONS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
