name: CodeReview at MergeRequest

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check code syntax
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install root modules
        run: npm install

      - name: Install service modules
        run: npm run i

      - name: Run ESLint
        run: npx eslint . --ext .ts,.vue
